DROP FUNCTION IF EXISTS BIG_TIME_TO_SEC;
DELIMITER $$
CREATE FUNCTION BIG_TIME_TO_SEC(TIME TEXT)
	RETURNS BIGINT
 	DETERMINISTIC
 	READS SQL DATA
BEGIN
	DECLARE HEURES TEXT;
	DECLARE MINUTES CHAR(5);
	DECLARE SECONDES CHAR(5);

	IF (TIME IS NULL) THEN RETURN NULL; END IF;

	SET HEURES = SUBSTRING_INDEX(TIME, ":", 1);

	SET MINUTES = SUBSTRING(TIME FROM -5 FOR 2);

	SET SECONDES = SUBSTRING(TIME FROM -2 FOR 2);

	RETURN CAST(HEURES AS  UNSIGNED INTEGER)*3600 + CAST(MINUTES AS  UNSIGNED INTEGER)*60 + CAST(SECONDES AS  UNSIGNED INTEGER);
END;
$$
DELIMITER ;